### ISSUE TITLE
Incorrect (?) gem name in readme 

### ISSUE THREAD

**Issue by lucaswiman** [tomz/libsvm-ruby-swig#6]
In both OS X and Ubuntu, using RVM, ruby 1.9.2, I get the following error:

```
$ gem install tomz-libsvm-ruby-swig
ERROR:  Could not find a valid gem 'tomz-libsvm-ruby-swig' (>= 0) in any repository
ERROR:  Possible alternatives: libsvm-ruby-swig, hexgnu-libsvm-ruby-swig, liblinear-ruby-swig
$ gem install libsvm-ruby-swig
Fetching: libsvm-ruby-swig-0.4.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed libsvm-ruby-swig-0.4.0
1 gem installed
Installing ri documentation for libsvm-ruby-swig-0.4.0...
Building YARD (yri) index for libsvm-ruby-swig-0.4.0...
Installing RDoc documentation for libsvm-ruby-swig-0.4.0...
```

Should the name of the gem be updated?

**Comment by louismullie** [comment]
This is because the gem is on github.com, rather than on RubyGems. Using `sudo gem sources -a http://gems.github.com` before installing will solve your problem.

That being said, I think many people would appreciate if @tomz pushed the gem to RubyGems. That way, we can require the library as a dependency in other gems!

**Comment by tomz** [comment]
Ok I will figure that out as soon as I get a chance.

Thanks,
Tom

**Comment by louismullie** [comment]
Cool, thanks. Same would be nice for liblinear-ruby-swig!
